name: release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: checkout
        run: git fetch --prune --unshallow
      - name: pipenv
        run: pip install pipenv && pipenv sync -d 
        run: make dist
      - name: distribute application
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{secrets.twine_password }}
          packages_dir: dist/
